networks:
  test-bank-net:

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_TEST_USERNAME}
      - POSTGRES_PASSWORD=${DB_TEST_PASSWORD}
      - POSTGRES_DB=test-bank-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - test-bank-net

volumes:
  pgdata:
